const palette = {
  // Mahalle brand
  night: "#0B0F1F",
  nightSoft: "#141A2E",
  nightCard: "#1B2238",
  amber: "#E9B342",
  amberSoft: "#F5C871",
  brick: "#B5443A",
  cream: "#F4ECDA",
  textHi: "#F4ECDA",
  textMid: "#B7B6C4",
  textLow: "#7E7C92",
  border: "#2C3350",
  good: "#4FB794",
  bad: "#E5654E",
  ghost: "#5A5872",
};

const colors = {
  light: {
    text: palette.textHi,
    tint: palette.amber,
    background: palette.night,
    foreground: palette.textHi,
    card: palette.nightCard,
    cardForeground: palette.textHi,
    primary: palette.amber,
    primaryForeground: palette.night,
    secondary: palette.nightSoft,
    secondaryForeground: palette.textHi,
    muted: palette.nightSoft,
    mutedForeground: palette.textMid,
    accent: palette.brick,
    accentForeground: palette.cream,
    destructive: palette.bad,
    destructiveForeground: palette.cream,
    border: palette.border,
    input: palette.border,
  },
  dark: {
    text: palette.textHi,
    tint: palette.amber,
    background: palette.night,
    foreground: palette.textHi,
    card: palette.nightCard,
    cardForeground: palette.textHi,
    primary: palette.amber,
    primaryForeground: palette.night,
    secondary: palette.nightSoft,
    secondaryForeground: palette.textHi,
    muted: palette.nightSoft,
    mutedForeground: palette.textMid,
    accent: palette.brick,
    accentForeground: palette.cream,
    destructive: palette.bad,
    destructiveForeground: palette.cream,
    border: palette.border,
    input: palette.border,
  },
  radius: 14,
  brand: palette,
};

export default colors;
